package TestCase::CompileError::CallSub::NotFound {
  sub main : int () {
    NOT_FOUND_SUB();
  }
}
